add_newline = false
# =====================================================
# Configurations
# =====================================================
format = """$directory$character"""
palette = "monochrome"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
# vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[dotnet]
format = '[$symbol($version )(🎯 $tfm )]($style) '
symbol = '.NET '
style = 'bold cyan'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln']
heuristic = false
version_format = '${major}'

[git_branch]
format =  '[$branch(:$remote_branch)]($style) '

[gcloud]
disabled = true

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style) '
disabled = true
style = 'bold blue'
symbol = "AWS "

[golang]
format = '[$symbol](bold cyan) '
symbol = "GO "

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

# =====================================================
# Palletes Definitions
# =====================================================
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.monochrome]
grey = "#777777"
none = "#777777"
white = "#777777"
rosewater = "#777777"
flamingo = "#777777"
pink = "#777777"
mauve = "#777777"
maroon = "#777777"
peach = "#777777"
sky = "#777777"
sapphire = "#777777"
blue = "#777777"
lavender = "#777777"
text = "#777777"
subtext1 = "#777777"
subtext0 = "#777777"
overlay2 = "#777777"
overlay1 = "#777777"
overlay0 = "#777777"
surface2 = "#777777"
surface1 = "#777777"
surface0 = "#777777"
base = "#777777"
mantle = "#777777"
crust = "#777777"
background = "#777777"
current_line = "#777777"
foreground = "#777777"
comment = "#777777"
cyan = "#777777"
green = "#777777"
orange = "#777777"
purple = "#777777"
red = "#777777"
yellow = "#777777"